---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: dell-csm-operator
  namespace: openshift-operators
  annotations:
    ran.openshift.io/ztp-deploy-wave: "2"
spec:
  targetNamespaces:
  - openshift-operators
