---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "example-multinode-site"
  namespace: "ztp-site"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    sites: "standard"
  # du-profile: "v4.10"
  mcp: "worker"
  sourceFiles:
    - fileName: StorageClass.yaml
      policyName: "config-policy"
